title: [ghostly-developer, a beginner's journey]
theme: minima
author: ghostly-developer
email: ranggagunarto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey there person! I'm a beginner software developer learning new languages, techniques and generally exploring the world of programming and software development.
  As of current i have learned python and cpp and have made a few programs and games with cpp and python. 
  I will regularly update this blog on what i learned, made or just my general thoughts.

# social links
github_username:  ghostly-developer

show_excerpts: true # set to false to remove excerpts on the homepage
